---
# EC2 dynamic invetory create different permutations of host collections based on instance properties such as tags.
# See http://codeheaven.io/15-things-you-should-know-about-ansible/ item 12 for more info.

- name: Install/upgrade Python
  hosts: tag_python 
  become: yes
  become_method: sudo
  gather_facts: false
  pre_tasks:
    - raw: sudo apt-get -y install python

- name: Install Python pip
  hosts: tag_python
  become: yes
  become_method: sudo
  gather_facts: false
  roles:
    - pip

- name: Install Docker on tagged hosts
  hosts: tag_docker
  gather_facts: true
  become: true
  become_method: sudo
  tasks:
    - name: Install docker-py
      pip: name=docker-py state=latest
  roles:
    - docker

- name: Install DCOS bootstrap on tagged host
  hosts: tag_dcos_bootstrap
  gather_facts: true
  become: true
  become_method: sudo
  roles:
    - dcos-bootstrap

- name: Install DCOS master, slave and public slaves on tagged hosts
  hosts: tag_dcos_cluster_node
  gather_facts: true
  roles:
    - dcos

- name: Install DCOS cli on DCOS controller hosts
  hosts: tag_dcos_controller[0]
  gather_facts: true
  roles:
    - dcos-controller

