---
# EC2 dynamic invetory create different permutations of host collections based on instance properties such as tags.
# See http://codeheaven.io/15-things-you-should-know-about-ansible/ item 12 for more info.

- name: Install/upgrade Python
  hosts: tag_python 
  become: yes
  become_method: sudo
  gather_facts: false
  pre_tasks:
    - raw: sudo apt-get -y install python

- name: Install Java on tagged hosts
  hosts: tag_java
  gather_facts: true
  roles:
    - java

- name: Install Docker on tagged hosts
  hosts: tag_docker
  gather_facts: true
  roles:
    - docker

- name: Install Zookeeper on tagged hosts
  hosts: tag_zookeeper
  gather_facts: true
  roles:
    - zookeeper

- name: Install Mesos on tagged hosts
  hosts: tag_mesos_master
  gather_facts: true
  roles:
    - { role: mesos, zookeeper_hostnames: "{{ groups.tag_zookeeper | join(':' + zookeeper_client_port + ',')  }}:{{ zookeeper_client_port  }}" }

- name: Install Mesos slaves on tagged hosts
  hosts: tag_mesos_slave
  gather_facts: true
  roles:
    - { role: mesos, mesos_containerizers: "docker,mesos", mesos_install_mode: "slave", zookeeper_hostnames: "{{ groups.tag_zookeeper | join(':' + zookeeper_client_port + ',')  }}:{{ zookeeper_client_port  }}" }

- name: Install Marathon on tagged hosts
  hosts: tag_marathon
  gather_facts: true
  roles:
    - { role: marathon, zookeeper_hostnames: "{{ groups.tag_zookeeper | join(':' + zookeeper_client_port + ',')  }}:{{ zookeeper_client_port  }}" }

- name: Install K8s on tagged hosts
  hosts: tag_k8s
  gather_facts: true
  vars:
    repository: "deb https://apt.dockerproject.org/repo ubuntu-trusty main"
    install_apparmor: true
  roles:
    - docker
    - k8s

- name: Install DCOS bootstrap on tagged host
  hosts: tag_dcos_bootstrap
  gather_facts: true
  roles:
    - dcos_bootstrap

- name: Install DCOS master, slave and public slaves on tagged hosts
  hosts: tag_dcos_cluster_node
  gather_facts: true
  roles:
    - dcos

- name: Install DCOS cli on DCOS controller hosts
  hosts: tag_dcos_controller[0]
  gather_facts: true
  roles:
    - dcos_controller

